kube2consul:
 command: --kube_master_url=http://kubemaster.service.consul:8080 --consul-agent=http://test_consul:8500 --kube-sync=30 --consul-sync=30
 build: .
 links:
 - consul
consul:
 image: gliderlabs/consul-server:0.6
 command: --bootstrap
 container_name: "test_consul"
 restart: always
